### ISSUE TITLE
Wrong icon size in electric network info screen

### ISSUE THREAD

**Issue by SteveS8** [ChurchOrganist/Long_Range_Radar#8] opened 2020-05-20 02:25 UTC
The icon shown in the power consumption screen seems to be twice the size it should be

**Comment by ChurchOrganist** [comment] 2020-06-25 08:54
That's weird - no idea what's causing that - will look into it shortly

**Comment by ChurchOrganist** [comment] 2020-06-25 09:18
OK I've worked out what the problem is - a fix will be out soon

**Comment by ChurchOrganist** [comment] 2020-07-08 13:39
This is now fixed for the next release. As it's so minor I shall be including it with the fast replace update I'm currently working on.

**Closed as completed** 2020-07-08 13:40 UTC
